pepc: work-around 'TypeError' argparse exception
In some system 'pepc' crashes when it is run without arguments:

$ pepc
Traceback (most recent call last):
  ...
  File "/usr/lib/python3/dist-packages/pepctool/_Pepc.py", line 45, in parse_args
    args, uargs = super().parse_known_args(*args, **kwargs)
TypeError: cannot unpack non-iterable NoneType object

This happens because 'parse_unknown_args()' crashes when no arguments are
provided. Work this around by handling the "no argument" special case.

Improve 'pepc' error message while on it.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>