SSHProcessManager: homogenize exception messages for file object
In this patch, manually converted exceptions e.g., 'UnicodeError', have the same
format as exceptions caught by 'WrapException()', e.g. 'PermissionDenied'.
Also now all exceptions raised by file object in 'SSHProcessManager' and
'LocalProcessManager' have the same format.

Caught by 'WrapException()':

pepc: error: failed to set EPB on host 'snr0':
  method 'write()' failed for file '/proc/cpuinfo':
    PermissionError: Permission denied

Manually converted in '_write_()':

pepc: error: failed to set EPB on host 'snr0':
  method 'write()' failed for file '/proc/cpuinfo':
    AttributeError: 'int' object has no attribute 'encode
The data to write must be a string

Signed-off-by: Niklas Neronin <niklas.neronin@intel.com>