Exception: allow for setting attributes via constructor
Sometimes it is required to pass more than just a message via an exception,
which can be done via exception object attributes. Make it easier to do by
allowing building an exception object with keyword arguments, which will be
translated to exception object attributes.

Example:

raise Error("message", cpu=5)

This will add the 'cpu' attribute with value 5.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>