Exception: fix python-3.9 crash
Fix python crash with the following symptom:

ExceptionType = type[Error] | type[ErrorTimeOut] | type[ErrorExists] | type[ErrorNotFound] | \
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'

This is because "|" operator is not supported in python-3.9, and
'from __future__ import annotations' does not help in this particular case (but
helps in most other cases).

So use the old-style 'typing.Union' instead.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>