Exception: recently introduced regression
Fix this crash:

  File "pepclibs/helperlibs/Exceptions.py", line 22, in __init__
    for key, val in kwargs:
ValueError: too many values to unpack (expected 2)

It was introduced few commits ago.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>