_FeaturedMSR: fix bug
This commit:
	d4ef065 msr: reduce featured MSR code duplication

introduced a bug which leads to the following crash:

  File "pepclibs/msr/_FeaturedMSR.py", line 126, in _create_features_dict
    for finfo in features.values():
AttributeError: 'NoneType' object has no attribute 'values'

Fix this bug.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>