Procs: fix 'no _dbg_ attribute' crash
One of the recent patches intruduced this regression:

Error:     File "pepclibs/helperlibs/_Procs.py", line 108, in read_pid
Error:       task._dbg_("_read_pid: reading PID for command: %s", task.cmd)
Error:   AttributeError: 'Popen' object has no attribute '_dbg_'

Fix it.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>