pepclibs: fix python3.9 compatibility issue
In some cases python3.9 backport does not support | and requires a union. Fix
several issues related to this, here is one of them:

  File "python3.9/site-packages/pepctool/_PepcPrinter.py", line 370, in _format_value_human
    cval = cast(list[float | int], val)
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>