_FeaturedMSR: Remove junk import that is causing a crash
Fix the following crash:

  File "lib/python3.13/site-packages/pepclibs/msr/_FeaturedMSR.py", line 23, in <module>
    from tkinter import E
  ModuleNotFoundError: No module named 'tkinter'

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>