LocalProcessManager: prevent error in 'open()' when byte-mode is used
This patch fixes the following bug which is caused by using 'open()' with
byte-mode:

File "/pepclibs/helperlibs/LocalProcessManager.py", line 303, in open
  fobj = open(path, mode, encoding="utf-8") # pylint: disable=consider-using-with
ValueError: binary mode doesn't take an encoding argument

This bug was introduced in v1.3.34.

Signed-off-by: Adam Hawley <adam.james.hawley@intel.com>