LocalProcessManager: retry directory tree removal
The shutil.rmtree() fails sometimes with:
OSError: [Errno 39] Directory not empty

This might be because of unfinished file
operations in the directory. Retry removal
few times.

Signed-off-by: Antti Laakso <antti.laakso@intel.com>